johnpangalos/wiggles

- .travis.yml
This should now be done with the netlify/github built in integration... which is pretty sweet. Nice that it is done for you.
> 2 automate frontend

- README.md
- package.json
- public/index.html
- src/App.js
- src/App.test.js
- src/setupTest.js
- src/setupTests.js
- src/styles/loading-spinner.css
- yarn.lock
resolves #3 
Uses firebase as a backend as it does everything we need and rather quickly
> Adding firebase and login to app

- src/App.js
resolves #14 
Adding email whitelisting in as a firebase function and then redirecting anyone without the proper claim.
> Adding in support for email whitelisting

- src/App.js
- src/Login.js
Also putting in logic to redirect to where the user came from
> Fixing logic error

- src/components/Alert.js
This was not usable from a phone, increasing the size to 24px standard
> Increasing the size of the x on the Alert

- public/index.html
- src/containers/Feed.js
- src/index.js
- src/styles/index.css
- Adding the library lozad for lazy loading
- Showing a loading spinner when loading images
- Only loading the first two images
> Add lazy loading for feed

- src/containers/Feed.js
Showing the newly generated web urls in the feed so we can reduce
bandwith especially on mobile devices.
> Using lower bandwidth photos url

- src/containers/ImageUpload.js
Listening to the status as the hook function runs to give the user a
better upload experience.
> Adding staged upload

- package.json
- public/index.html
- src/App.js
- src/components/Image.js
- src/components/ProfileImage.js
- src/components/index.js
- src/containers/Feed.js
- src/containers/ImageUpload.js
- src/containers/Profile.js
- src/containers/index.js
- yarn.lock
- Also added support for web and thumbnails
- Also added correct orientation of uploaded images
> Add a more detailed profile

- public/index.html
- src/components/Image.js
- src/components/transitions/Fade.js
- src/containers/Feed.js
- src/containers/Login.js
- src/styles/index.css
- Using animate.css instead of custom created animations
- Changing images to load with a fade in
- Removing loading spinner for images as it looks better without it
> Adding better animation support

- src/App.js
- src/components/Image.js
- src/components/transitions/Fade.js
Fade transition was causing a wierd flicker especially during
transitions. This should also hopefully fix the flicker issue for now
> Get rid of flicker from fade transition

- src/App.js
- src/components/Toolbar.js
- src/components/index.js
- src/components/transitions/Fade.js
- src/components/transitions/SlideInDown.js
- src/components/transitions/SlideUp.js
- src/components/transitions/index.js
- src/containers/Feed.js
- src/containers/Profile/components/SelectToolbar.js
- src/containers/Profile/components/Thumbnails.js
- src/containers/Profile/index.js
- src/styles/index.css
- tailwind.config.js
- Also makes profile thumbnails more responsive
- Moves toolbare out to it's own component
> Add Slide down transition

- public/manifest.json
Adding required fields for the add to homescreen prompt to show
> Update to manifest for get prompt

- src/components/Image.js
- src/components/ProfileImage.js
- src/containers/Feed.js
- Added the ability to see the user who uploaded an image
> Add user and date to uploaded images

- src/App.js
- src/constants/index.js
- src/containers/ImageUpload/components/SubmitScreen.js
- src/containers/ImageUpload/index.js
- src/reducers/index.js
- src/reducers/user.js
- This fixes a problem with user being null. This isn't a great fix but
I was trying to move to redux anyway...
> Move user to reducer

- .eslintrc.json
- package.json
- src/containers/ImageUpload/components/SubmitScreen.js
- src/containers/ImageUpload/index.js
- yarn.lock
This makes it so the app no longer waits for post processing
> Add linter and temp fix for flow

- src/containers/Profile/actions.js
- src/containers/Profile/components/Thumbnails.js
- src/containers/Profile/index.js
- src/containers/Profile/reducer.js
> Fix delete post

- public/index.html
- yarn.lock
> Adding update pwa support (hopefully)

- public/index.html
- src/serviceWorker.js
> Remove the pwa update as it doesn't work

- src/components/Image.js
- src/containers/Feed.js
- src/containers/PostWrapper.js
- Reintroduced lozad
- Added a button to reload the page for people not on android chrome
pwa's (i.e. firefox/safari)
> Add in refresh button and add back in lazy loading

- public/index.html
- src/components/Image.js
- src/containers/Feed.js
- src/containers/ImageWrapper.js
- src/containers/Profile/components/Thumbnails.js
- src/index.js
- Actually using thumbnails for images
- Fixing it so that the presistence is only in production
> Move persistence to js, enable thumbnails

- src/App.js
- src/components/Post.js
- src/components/Tabs.js
- src/containers/ImageUpload/components/SubmitScreen.js
- src/containers/ImageUpload/components/UploadScreen.js
- src/containers/ImageUpload/index.js
- src/containers/Upload.js
- tailwind.config.js
- Max height on posts based on screen size
- Remove some of the float bloat
> Refactor some of the css and html

- package.json
- tailwind.config.js
- yarn.lock
> Moving to tailwind 2.0

- package.json
- src/App.js
- src/components/Button.js
- src/containers/Profile/components/Thumbnails.js
- src/index.tsx
- src/pages/Upload.tsx
- tailwind.config.js
- yarn.lock
This fixes a bug on the profile page and refactors upload so that it's
quicker and supports multiple uploads
> Refactor upload

- web/.env.staging
- web/package.json
- web/public/sw.js
- web/src/App.tsx
- web/src/index.tsx
- web/src/register-sw.ts
Minimum requirements for android install
> Add basic PWA
